# Generated by Django 5.1 on 2024-08-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
