# Generated by Django 5.1 on 2024-08-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_conversation_user_id_alter_conversation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
